"""
Build data.js — bundles all JSON data files into a single JS file
so the dashboard works without a web server (file:// protocol).
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
OUTPUT = os.path.join(os.path.dirname(__file__), "data.js")

FILES = [
    "dim_fund",
    "fact_aum",
    "fact_performance",
    "fact_nav",
    "fact_transactions",
    "monthly_sip_inflows",
    "category_inflows",
    "industry_folio_count",
    "benchmark_indices",
]

lines = [
    "// Auto-generated by build_data_js.py — do not edit manually\n",
    "window.__DASHBOARD_DATA__ = {};\n\n",
]

for name in FILES:
    path = os.path.join(DATA_DIR, name + ".json")
    with open(path, encoding="utf-8") as fp:
        raw = fp.read()
    lines.append(f'window.__DASHBOARD_DATA__["{name}"] = {raw};\n\n')

with open(OUTPUT, "w", encoding="utf-8") as fp:
    fp.writelines(lines)

size_mb = os.path.getsize(OUTPUT) / 1024 / 1024
print(f"[OK] data.js written — {size_mb:.2f} MB")
